projects:
  post-service:
    schemaPath: schemas/post-service.graphql
    extensions:
      endpoints:
        default: http://localhost:4001
  user-service:
    schemaPath: schemas/user-service.graphql
    extensions:
      endpoints:
        default: http://localhost:4002